services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flutter-capacitacion
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_URL=jdbc:postgresql://db:5432/flutter-capacitacion
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SPRING_PROFILES_ACTIVE=development
    depends_on:
      db:
        condition: service_healthy
    restart: always
    # Health check to ensure the app is running properly
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 
    # Development mode configuration (only active when using --watch)
    develop:
      watch:
        - action: rebuild
          path: ./src/main
        - action: rebuild
          path: ./pom.xml
        - action: rebuild
          path: ./Dockerfile

volumes:
  db:
    driver: local
